# Generated by Django 3.1.6 on 2021-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('accno', models.CharField(max_length=15)),
                ('mpin', models.CharField(max_length=6, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('phonenumber', models.CharField(max_length=12)),
                ('balance', models.IntegerField(default=3000)),
            ],
        ),
    ]
